deploy_demo:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  environment:
    name: demo
    url: http://proof-of-toss-demo.axioma.lv/
# deploy will run on shared runner "Deploy on vs04"
  tags:
    - demo
# the following configuration will deploy every commit of master branch
  # when: manual
  only:
    - master
# actual deployment commands starts here
# need a testrpc running on localhost
# mkdir testrpc_db
# npm install ganache-cli
# nohup ./node_modules/ganache-cli/build/cli.node.js --db=testrpc_db --account="0x1f8969bdcfdfe9c17580a43522a258543238cb9df11a4694be3e5fc9b0d1edea,100000000000000000000" --account="0x746dfbc1f0518516bdd42821435d297681338ff1d950b7e6b7d7480ca64375c6,100000000000000000000" --account="0x5b4c3249a068b0b3e14608993226450b9a635613cfa7fea0e045f349f5f1b6b4,100000000000000000000" --account="0xcc844e935f39a23e7061670c491eb2e8c95dfe8206bcb47c712b4c399212e893,100000000000000000000" --account="0xd83fa9e30c43be2fb10be664ec4fcecd9fc66ef6f4c084e1a28f381f85b66792,100000000000000000000" --account="0x8f838e8e3bb98b43f6ac545bc757583fbf2e965489e49d4709034ce92d86df21,100000000000000000000" --account="0x831baf12669d55a724486c82d22a178159aa0a71381bf24c84e67d17c7ff387a,100000000000000000000" --account="0x682218d983fa9b276792c60e6ad9e58762fa3068414c17a5f5742cd5130bf741,100000000000000000000" --account="0x42a9bd8cb5b90e2a9a4cd894ee04fdad2f70306f935cef37a619db22a53ef2bf,100000000000000000000" --account="0x48e8c82d4c25e31ee48af9d5cd72e51ef190ad312042d656495c625318229135,100000000000000000000" &
# to stop testrpc:
# kill `ps -a |grep "[g]anache-cli/build/cli.node.js"|cut -d" " -f 1`
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/config.json $CI_PROJECT_DIR/src/data/
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/private_config.json $CI_PROJECT_DIR/src/data/
    - mkdir $CI_PROJECT_DIR/build
    - rsync -hrlv --delete /srv/www/proof-of-toss-demo.axioma.lv/htdocs/build/ $CI_PROJECT_DIR/build/
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate
    - npm run build
    - echo "Deploy to Demo"
    - rsync -hrlv --delete --exclude=.git --exclude=node_modules --exclude=npm-debug.log --exclude=testrpc_db --exclude=nohup.out $CI_PROJECT_DIR/ /srv/www/proof-of-toss-demo.axioma.lv/htdocs/
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 restart event_watcher"

deploy_demo_reindex:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  environment:
    name: demo
    url: http://proof-of-toss-demo.axioma.lv/
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/config.json $CI_PROJECT_DIR/src/data/
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/private_config.json $CI_PROJECT_DIR/src/data/
    - mkdir $CI_PROJECT_DIR/build
    - rsync -hrlv --delete /srv/www/proof-of-toss-demo.axioma.lv/htdocs/build/ $CI_PROJECT_DIR/build/
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate -f 3
    - npm run build
    - echo "Deploy to Demo"
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 stop event_watcher"
    - rm -rf /srv/www/proof-of-toss-demo.axioma.lv/htdocs/scripts/cache_state.json
    - rsync -hrlv --delete --exclude=.git --exclude=node_modules --exclude=npm-debug.log --exclude=testrpc_db --exclude=nohup.out $CI_PROJECT_DIR/ /srv/www/proof-of-toss-demo.axioma.lv/htdocs/
    - npm run renew_es_index
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 start event_watcher"

deploy_demo_contracts:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  environment:
    name: demo
    url: http://proof-of-toss-demo.axioma.lv/
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/config.json $CI_PROJECT_DIR/src/data/
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/private_config.json $CI_PROJECT_DIR/src/data/
    - mkdir $CI_PROJECT_DIR/build
    - rsync -hrlv --delete /srv/www/proof-of-toss-demo.axioma.lv/htdocs/build/ $CI_PROJECT_DIR/build/
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate -f 3
    - npm run build
    - echo "Deploy to Demo"
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 stop event_watcher"
    - rm -rf /srv/www/proof-of-toss-demo.axioma.lv/htdocs/scripts/cache_state.json
    - rsync -hrlv --delete --exclude=.git --exclude=node_modules --exclude=npm-debug.log --exclude=testrpc_db --exclude=nohup.out $CI_PROJECT_DIR/ /srv/www/proof-of-toss-demo.axioma.lv/htdocs/
    - npm run sync_whitelist
    - npm run prepare_demo_token
    - npm run renew_es_index
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 start event_watcher"

deploy_demo_full:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  environment:
    name: demo
    url: http://proof-of-toss-demo.axioma.lv/
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/config.json $CI_PROJECT_DIR/src/data/
    - cp /srv/www/proof-of-toss-demo.axioma.lv/htdocs/src/data/private_config.json $CI_PROJECT_DIR/src/data/
    - mkdir $CI_PROJECT_DIR/build
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate --reset
    - npm run build
    - echo "Deploy to Demo"
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 stop event_watcher"
    - rm -rf /srv/www/proof-of-toss-demo.axioma.lv/htdocs/scripts/cache_state.json
    - rsync -hrlv --delete --exclude=.git --exclude=node_modules --exclude=npm-debug.log --exclude=testrpc_db --exclude=nohup.out $CI_PROJECT_DIR/ /srv/www/proof-of-toss-demo.axioma.lv/htdocs/
    - npm run sync_whitelist
    - npm run prepare_demo_token
    - npm run renew_es_index
    - ssh testrpc@vs04.axioma.lv "/usr/local/bin/pm2 start event_watcher"

deploy_production:
  stage: deploy
  environment:
    name: deploy_production
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - scp $AWS_HOST_LOGIN:/home/ec2-user/proof-of-toss/src/data/config.json src/data/config.json
    - mkdir $CI_PROJECT_DIR/build
    - rsync -hrlv --delete /home/gitlab-runner/toss_production_build/build/ $CI_PROJECT_DIR/build/
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate
    - npm run build
    - echo "Deloy to production server"
    - node scripts/deploy.js $AWS_DEPLOY_ACCESS_KEY_ID $AWS_DEPLOY_SECRET_ACCESS_KEY $AWS_CLOUDFRONT_DISTRIBUTION_ID
    - ssh $AWS_HOST_LOGIN "cd /home/ec2-user/proof-of-toss; git pull origin master; npm install; pm2 restart event_watcher"

deploy_production_reindex:
  stage: deploy
  environment:
    name: deploy_production
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - scp $AWS_HOST_LOGIN:/home/ec2-user/proof-of-toss/src/data/config.json src/data/config.json
    - mkdir $CI_PROJECT_DIR/build
    - rsync -hrlv --delete /home/gitlab-runner/toss_production_build/build/ $CI_PROJECT_DIR/build/
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate
    - npm run build
    - echo "Deloy to production server"
    - node scripts/deploy.js $AWS_DEPLOY_ACCESS_KEY_ID $AWS_DEPLOY_SECRET_ACCESS_KEY $AWS_CLOUDFRONT_DISTRIBUTION_ID
    - ssh $AWS_HOST_LOGIN "cd /home/ec2-user/proof-of-toss; git pull origin master; npm install; pm2 stop event_watcher; npm run renew_es_index; rm -f scripts/cache_state.json; pm2 restart event_watcher"

deploy_production_contracts:
  stage: deploy
  environment:
    name: deploy_production
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - scp $AWS_HOST_LOGIN:/home/ec2-user/proof-of-toss/src/data/config.json src/data/config.json
    - mkdir $CI_PROJECT_DIR/build
    - rsync -hrlv --delete /home/gitlab-runner/toss_production_build/build/ $CI_PROJECT_DIR/build/
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate -f 3
    - npm run build
    - echo "Deloy to production server"
    - node scripts/deploy.js $AWS_DEPLOY_ACCESS_KEY_ID $AWS_DEPLOY_SECRET_ACCESS_KEY $AWS_CLOUDFRONT_DISTRIBUTION_ID
    - echo "Deloy to event-watcher server"
    - scp -r ./build $AWS_HOST_LOGIN:/home/ec2-user/proof-of-toss/
    - ssh $AWS_HOST_LOGIN "cd /home/ec2-user/proof-of-toss; git pull origin master; npm install; pm2 stop event_watcher; npm run renew_es_index; rm -f scripts/cache_state.json; pm2 restart event_watcher"

deploy_production_full:
  stage: deploy
  environment:
    name: deploy_production
  tags:
    - demo
  when: manual
  only:
    - master
  script:
    - echo "Build app"
    - source /opt/rh/devtoolset-2/enable
    - rm -rf node_modules
    - nvm use system
    - npm install
    - ./truffle-config-gen.sh
    - scp $AWS_HOST_LOGIN:/home/ec2-user/proof-of-toss/src/data/config.json src/data/config.json
    - mkdir $CI_PROJECT_DIR/build
    - ./node_modules/truffle/build/cli.bundled.js --network ropsten migrate --reset
    - npm run build
    - echo "Deloy to production server"
    - node scripts/deploy.js $AWS_DEPLOY_ACCESS_KEY_ID $AWS_DEPLOY_SECRET_ACCESS_KEY $AWS_CLOUDFRONT_DISTRIBUTION_ID
    - echo "Deloy to event-watcher server"
    - scp -r ./build $AWS_HOST_LOGIN:/home/ec2-user/proof-of-toss/
    - ssh $AWS_HOST_LOGIN "cd /home/ec2-user/proof-of-toss; git pull origin master; npm install; pm2 stop event_watcher; npm run renew_es_index; rm -f scripts/cache_state.json; pm2 restart event_watcher"

