version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch_540
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana_540
    environment:
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  headPlugin:
    image: mobz/elasticsearch-head:5
    container_name: head_540
    ports:
      - 9100:9100

  rsk:
    build:
      context: .
      dockerfile: docker/rsk/Dockerfile
    expose:
      - 4444
    ports:
      - 50505:50505
    volumes:
      - ./docker/rsk/rsk:/etc/rsk

  testrpc:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - rsk
      - testrpc
    links:
      - rsk:rsk
      - testrpc:testrpc
    volumes:
      - ./config:/home/app/config
      - ./contracts:/home/app/contracts
      - ./migrations:/home/app/migrations
      - ./public:/home/app/public
      - ./scripts:/home/app/scripts
      - ./src:/home/app/src
      - ./test:/home/app/test
      - ./.babelrc:/home/app/.babelrc
      - ./elasticsearch.yml:/home/app/elasticsearch.yml
      - ./kibana.yml:/home/app/kibana.yml
      - ./package.json:/home/app/package.json
      - ./truffle.js:/home/app/truffle.js

volumes:
  esdata:
    driver: local